server:
  port: 10000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.220.10:3306/gulimall_pms

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
#      logic-delete-field: showStatus # Java对象字段名，不是数据库字段名
#      logic-delete-value: 0
#      logic-not-delete-value: 1
  mapper-locations: classpath:/mapper/**/*.xml


logging:
  level:
    com.test.gulimall: debug