server:
  port: 10000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.220.10:3306/gulimall_pms
  redis:
    host: 192.168.220.10
    port: 6379

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false
  # 指定spring cache的类型 spring.cache.type
  cache:
    type: redis
    redis:
      time-to-live: 3600000
#      key-prefix: CACHE_
      use-key-prefix: true
      #允许缓存null值， 防止缓存穿透问题
      cache-null-values: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
#      logic-delete-field: showStatus # Java对象字段名，不是数据库字段名
#      logic-delete-value: 0
#      logic-not-delete-value: 1
  mapper-locations: classpath:/mapper/**/*.xml


logging:
  level:
    com.test.gulimall: error