server:
  port: 7000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.220.10:3306/gulimall_sms
  application:
    name: gulimall-coupon
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml
